### ISSUE TITLE
Error: The module '/usr/lib/node_modules/homebridge-nikobus/node_modules/serialport/build/Release/serialport.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 48. This version of Node.js requires NODE_MODULE_VERSION 51. Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by pagaille** [timschuerewegen/homebridge-nikobus#2]
Hi again,

I'm still struggling to use your module because of version clashes.

Using node 6, I'm able to start homebridge with the nikobus module but can't add the accessory to my iOS device because of this error apparently fixed in node V8+ :

```
TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
```

Sadly, when using any node version upper than V6, the nikobus module fails : 

```
# homebridge
[10/9/2019, 2:55:42 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/9/2019, 2:55:42 PM] ---
[10/9/2019, 2:55:42 PM] ====================
[10/9/2019, 2:55:42 PM] ERROR LOADING PLUGIN homebridge-nikobus:
[10/9/2019, 2:55:42 PM] Error: The module '/usr/lib/node_modules/homebridge-nikobus/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/usr/lib/node_modules/homebridge-nikobus/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-nikobus/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[10/9/2019, 2:55:42 PM] ====================
[10/9/2019, 2:55:42 PM] No plugins found. See the README for information on installing plugins.
[10/9/2019, 2:55:42 PM] Loading 1 platforms...
[10/9/2019, 2:55:42 PM] Error: The requested platform 'Nikobus' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[10/9/2019, 2:55:42 PM] Got SIGTERM, shutting down Homebridge...
```

Can you help ? 😊 Txs

**Comment by timschuerewegen** [comment]
Can you try again? I changed the serialport version. I don't have a nikobus installation myself so I can't really test if it works.

**Comment by pagaille** [comment]
Thanks ! It works now, at least using sudo.

However, there is still something wrong when flashing the QR code:

```
[10/25/2019, 9:48:34 PM] Homebridge is running on port 52460.
[10/25/2019, 9:48:34 PM] [Nikobus] serial rx [] (cr)
[10/25/2019, 9:48:34 PM] [Nikobus] received command: 
[10/25/2019, 9:49:02 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
```

**Comment by pagaille** [comment]
NB without using sudo (still not sure what I should use) I get this when installing : 

```
# npm install -g homebridge-nikobus 

> @serialport/bindings@2.0.8 install /usr/local/lib/node_modules/homebridge-nikobus/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-nikobus/node_modules/@serialport/bindings/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-nikobus/node_modules/@serialport/bindings/.node-gyp'
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-nikobus/node_modules/@serialport/bindings
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-25T19_57_13_656Z-debug.log
```

**Comment by timschuerewegen** [comment]
1. Yes, you need to use sudo when installing "serialport" or else it will fail with an error.
2. You probably need to install a newer node version to fix the "TypeError: "list" argument must be an Array of Buffers" error. See https://github.com/nfarina/homebridge/issues/2219 for the same error and a solution.

**Comment by pagaille** [comment]
It works. Thanks

I had to remove everything and reinstall everything without using sudo because... I was root 😊 And running a command as root is not the same as running it as "sudo root" as it seems.

Somehow running homebridge as sudo was triggering an ooold version of node, probably the one shipped by default with CentOS. Needless to say it was driving me nuts because `sudo node -v` is not the same as `node -v` even if you're root. Crazy.

Now, to be fair, it was by scientific interest that i wanted to try this out, but the usefulness of being able to switch a light on or off with your iPhone seems rather limited to me. I hoped some apple magic here but it seems you need an applet tv or HomePod for that. 

But look, I had fun with npm 😊  

Thanks !
